swagger: "2.0"
info:
  description: This is the swagger file for Go CVEs
  version: "1.0.0"
  title: Probable Security Vulnerabilities
consumes:
  - application/json
produces:
  - application/json

basePath: /cveapi

# Paths supported by the server application
paths:
  /pCVE:
    get:
      operationId: cve.read_all
      tags:
        - Read
      summary: probable CVEs list
      description: Read the entire list of probable CVEs
      parameters:
        - name: length
          in: query
          type: integer
          description: Number of CVEs to get from CVEs
          required: false
        - name: offset
          in: query
          type: integer
          description: Offset from beginning of list where to start gathering CVEs
          required: false
      responses:
        200:
          description: Successfully read CVEs list operation
          schema:
            $ref: "#/definitions/cvelist"

    post:
      operationId: cve.create
      tags:
        - Insert
      summary: Create a new CVE
      description: Insert a new CVE record
      consumes:
        - application/json
      parameters:
        - name: CVE
          in: body
          description: CVE JSON to update
          required: True
          schema:
            $ref: "#/definitions/cveinsert"
      responses:
        201:
          description: Successfully updated CVE

    delete:
      operationId: cve.delete
      tags:
        - Delete
      summary: Delete a CVE
      description: Delete a CVE
      consumes:
        - application/json
      parameters:
        - name: CVE
          in: body
          description: CVE JSON to delete
          required: True
          schema:
            $ref: "#/definitions/cvedelete"
      responses:
        201:
          description: Successfully deleted CVE

    put:
        operationId: cve.update
        tags:
          - Update
        summary: update the details of a CVE
        description: Update the details of a CVE
        consumes:
          - application/json
        parameters:
          - name: CVE
            in: body
            description: CVE JSON to update
            required: True
            schema:
              $ref: "#/definitions/cveupdate"
        responses:
          201:
            description: Successfully updated CVE details
  
  /pCVE/Status:
    put:
      operationId: cve.updatestatus
      tags:
        - Update Status
      summary: update the status of a CVE
      description: Update the status of a CVE
      consumes:
        - application/json
      parameters:
        - name: CVE
          in: body
          description: CVE JSON to update
          required: True
          schema:
            $ref: "#/definitions/cveupdatestatus"
      responses:
        201:
          description: Successfully updated CVE status
      

#Definitions of JSON object references
definitions:

  cveupdate:
    type: object
    properties:
      package:
        type: string
      cause_type:
        type: string
      issue_date:
        type: string
      issue_url:
        type: string
      fixed_date:
        type: string
      fixed_url:
        type: string
      commit_date:
        type: string
      commit_url:
        type: string
      identified_date:
        type: string
      identified_url:
        type: string
      files_changed:
        type: string
      cve_id:
        type: string
      cve_date:
        type: string
      flagged_score:
        type: string
      flagged_comments:
        type: string
      additional_info:
        type: string
      review_comments:
        type: string
      status:
        type: string
        description: new status of CVE
      id:
        type: integer
        description: Autogenerated ID of CVE to update
 
  cveupdatestatus:
    type: object
    properties:
      status:
        type: integer
        description: new status of CVE
      reviewed_by:
        type: string
        description: who is updating the status of CVE
      review_comments:
        type: string
        description: Any comments whle updating the status
      id:
        type: integer
        description: Autogenerated ID of CVE to update
  
  cvedelete:
    type: object
    properties:
      id:
        type: integer
        description: Autogenerated ID of CVE to update

  cveinsert:
    type: object
    properties:
      ecosystem:
        type: string
      package:
        type: string
      commit:
        type: string
      causeddate:
        type: string
      confidence:
        type: string
      status:
        type: string
  
  cvelist:
    type: object
    properties:
      ecosystem:
        type: string
      repository:
        type: string
      repo_url:
        type: string
      package:
        type: string
      cause_type:
        type: string
      issue_date:
        type: string
      issue_url:
        type: string
      fixed_date:
        type: string
      fixed_url:
        type: string
      commit_date:
        type: string
      commit_url:
        type: string
      identified_date:
        type: string
      identified_url:
        type: string
      files_changed:
        type: string
      review_status:
        type: integer
      reviewed_at:
        type: string
      cve_id:
        type: string
      cve_date:
        type: string
      flagged_score:
        type: string
      flagged_at:
        type: string
      flagged_comments:
        type: string
      additional_info:
        type: string
      review_comments:
        type: string
      id:
        type: string